apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: App1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/abdul-at/argo-app1.git
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
