apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
spec:
  generators:
  - list:
      elements:
        - service: app1
          appname: grafana
          repoURL: https://github.com/abdul-at/argo-app1.git
        - service: app2
          appname: loki-stack
          repoURL: https://github.com/abdul-at/argo-app2.git
    selector:
      matchLabels:
        env: staging
  template:
    metadata:
      name: 'applicationset'
    spec:
      project: default
      source:
        repoURL: {{ repoURL }}
        targetRevision: main
        path: helm/{{ appname }}
      destination:
        server: https://kubernetes.default.svc
        namespace: default
